# Generated by Django 5.1.3 on 2025-02-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='url',
            field=models.URLField(),
        ),
    ]
