# Generated by Django 5.1.3 on 2025-02-19 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notificacion_evaluacion_alter_documentopdf_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacion',
            name='visto',
        ),
        migrations.AlterField(
            model_name='documentopdf',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 11, 29, 12, 165680)),
        ),
    ]
