# Generated by Django 5.1.3 on 2025-02-10 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notificacion_visto_alter_notificacion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha_aparicion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
