# Generated by Django 5.1.3 on 2025-02-19 17:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_recomendacion_visto_alter_documentopdf_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='api.evaluacion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentopdf',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 12, 17, 35, 368144)),
        ),
    ]
