# Generated by Django 5.1.3 on 2025-02-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notificacion_fecha_aparicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='dni',
            new_name='cedula',
        ),
    ]
