# Generated by Django 5.1.3 on 2025-02-19 17:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recomendacion_evaluacion_alter_documentopdf_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='pregunta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='api.pregunta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentopdf',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 12, 26, 1, 322727)),
        ),
    ]
