# Generated by Django 5.1.3 on 2025-02-19 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recomendacion_pregunta_alter_documentopdf_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopdf',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 12, 53, 30, 511986)),
        ),
    ]
