# Generated by Django 5.1.3 on 2025-02-21 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_documentopdf_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='intentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentopdf',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 23, 40, 57, 16646)),
        ),
    ]
